"""Add wallet_address to users

Revision ID: da40985f66c8
Revises: 33f0537d5bd1
Create Date: 2025-04-22 16:17:51.530365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da40985f66c8'
down_revision: Union[str, None] = '33f0537d5bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('status', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('pdf_url', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_address')
    op.drop_column('deals', 'created_at')
    op.drop_column('deals', 'pdf_url')
    op.drop_column('deals', 'status')
    # ### end Alembic commands ###
