# ─────────────────────────────────────────────────────────────────────────────
#  Dockerfile (at repo root)
# ─────────────────────────────────────────────────────────────────────────────

# ─── 0) Use a Python runtime as our base
FROM python:3.11-slim AS base

# Ensure Python output is unbuffered and set default PORT to 8080
ENV PYTHONUNBUFFERED=1 \
    PORT=8080

WORKDIR /srv

# ─── 1) Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      git build-essential libffi-dev libpq-dev libjpeg-dev \
      libcairo2 libpango-1.0-0 libpangocairo-1.0-0 \
      libgdk-pixbuf2.0-0 shared-mime-info ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# ─── 2) Copy & install Python dependencies
COPY backend/requirements.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# ─── 3) Copy your backend application code
COPY backend/ ./backend

# ─── 4) Copy the exported Next.js frontend (must have been generated by `npm run export`)
#       Cloud Build will have run:
#         cd frontend && npm ci && npm run build && npm run export
#       so that `frontend/out/` already exists.
#
#       We copy it here into /srv/backend/static so that the backend can serve it.
#       You can adjust your FastAPI (or Starlette) code to mount this folder under "/"
COPY frontend/out/ ./backend/static/

# ─── 5) Adjust PYTHONPATH so Uvicorn can find your backend package
ENV PYTHONPATH=/srv/backend

# ─── 6) Expose port and start the server
EXPOSE 8080

#    We expect your FastAPI app (in backend/main.py) to do something like:
#      app.mount("/", StaticFiles(directory="static", html=True), name="frontend")
#    so that visiting "/" returns the Next.js‐exported index.html automatically.
CMD ["sh", "-c", "exec uvicorn backend.main:app --host 0.0.0.0 --port $PORT --proxy-headers"]