from __future__ import annotations

from pathlib import Path


APP_JS = Path("desktop/mac/src/app.js")


def _read() -> str:
    assert APP_JS.exists(), "desktop/mac/src/app.js not found"
    return APP_JS.read_text(encoding="utf-8")


def test_workflow_architect_load_preserves_generated_node_contract() -> None:
    text = _read()

    assert "function loadWorkflowArchitectReviewOntoCanvas()" in text
    assert "architect_review" in text
    assert "loaded_from_valid_review" in text

    # Generated node identity/config contract.
    assert "step.step_id" in text
    assert "step.node_type" in text
    assert "step.label" in text
    assert "step.config" in text

    # Safety/approval metadata contract.
    assert "risk_tier" in text
    assert "requires_approval" in text
    assert "dry_run_only" in text


def test_workflow_architect_loaded_graph_preserves_missing_connector_metadata() -> None:
    text = _read()

    assert "missing_connectors" in text
    assert "placeholder" in text.lower()
    assert "missing connector" in text.lower()


def test_workflow_architect_loaded_graph_forbids_live_send_tokens() -> None:
    text = _read().lower()

    load_start = text.index("function loadworkflowarchitectreviewontocanvas()")
    load_block = text[load_start : load_start + 6500]

    forbidden = [
        "users.messages.send",
        "send_message(",
        "live_execute",
    ]

    for token in forbidden:
        assert token not in load_block

    assert "live_send_enabled: false" in load_block


def test_workflow_architect_inspector_shows_generated_node_config() -> None:
    text = _read()

    assert "selectedNode.config" in text
    assert "JSON.stringify(selectedNode.config" in text or "JSON.stringify(selectedNode?.config" in text
    assert "Generated by Architect" in text


def test_workflow_architect_inspector_marks_approval_and_placeholder_nodes() -> None:
    text = _read().lower()

    assert "approval gate" in text or "approval required" in text
    assert "requires_approval" in text
    assert "placeholder" in text
    assert "blocked" in text
