ALIASES:
  "⊕_q": "quantum:⊕"
  "⊗_p": "physics:⊗"
  "⊗_s": "symatics:⊗"
  "~": "photon:≈"

COLLISIONS:
  "⊗": ["logic:⊗", "physics:⊗", "symatics:⊗"]
  "⊕": ["logic:⊕", "quantum:⊕"]
  "↔": ["logic:↔", "quantum:↔"]

PRIORITY_ORDER:
  - logic
  - math
  - physics
  - quantum
  - symatics
  - photon
  - control