import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional


class PilotArtifactBuilderViolation(Exception):
    pass


class PilotArtifactBuilderRuntime:
    """
    Phase 21D: safe artifact builder runtime for AION Pilot.

    The runtime creates draft artifacts inside the business container only.
    It does not publish, send, deploy, pay, book, escrow, or mutate live memory.
    """

    ALLOWED_ARTIFACT_TYPES = {
        "pdf",
        "document",
        "spreadsheet",
        "text",
        "markdown",
        "json",
    }

    BLOCKED_ACTIONS = {
        "send_email",
        "send_whatsapp",
        "publish_post",
        "deploy_site",
        "buy_domain",
        "payment",
        "booking",
        "escrow",
        "dispatch",
        "mutate_live_memory",
        "write_reputation",
    }

    @classmethod
    def canonical_hash(cls, payload: Dict[str, Any]) -> str:
        raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
        return "sha256:" + hashlib.sha256(raw).hexdigest()

    @classmethod
    def _safe_filename(cls, name: str) -> str:
        name = name.strip()
        if not name:
            raise PilotArtifactBuilderViolation("artifact_name_required")

        if "/" in name or "\\" in name or ".." in name:
            raise PilotArtifactBuilderViolation("unsafe_artifact_name_path_traversal_blocked")

        safe = re.sub(r"[^a-zA-Z0-9._-]+", "_", name)
        if safe.startswith("."):
            raise PilotArtifactBuilderViolation("hidden_artifact_name_blocked")
        return safe

    @classmethod
    def _assert_container_path(cls, container_root: str, candidate_path: Path) -> None:
        root = Path(container_root).resolve()
        target = candidate_path.resolve()
        try:
            target.relative_to(root)
        except ValueError as exc:
            raise PilotArtifactBuilderViolation("artifact_path_outside_business_container_blocked") from exc

    @classmethod
    def build_artifact_contract(
        cls,
        *,
        business_id: str,
        mission_id: str,
        mission_run_id: str,
        step_id: str,
        artifact_type: str,
        artifact_name: str,
        requested_by: str = "pilot",
        status: str = "draft_preview",
    ) -> Dict[str, Any]:
        if artifact_type not in cls.ALLOWED_ARTIFACT_TYPES:
            raise PilotArtifactBuilderViolation(f"unsupported_artifact_type:{artifact_type}")

        safe_name = cls._safe_filename(artifact_name)

        contract = {
            "contract_type": "aion.pilot.artifact_builder.contract.v1",
            "business_id": business_id,
            "mission_id": mission_id,
            "mission_run_id": mission_run_id,
            "step_id": step_id,
            "artifact_type": artifact_type,
            "artifact_name": safe_name,
            "requested_by": requested_by,
            "status": status,
            "live_external_side_effects_allowed": False,
            "raw_tool_execution_allowed": False,
            "business_container_required": True,
        }
        contract["artifact_contract_hash"] = cls.canonical_hash(contract)
        return contract

    @classmethod
    def build_container_relative_path(cls, contract: Dict[str, Any]) -> str:
        safe_name = cls._safe_filename(contract["artifact_name"])
        return (
            f"business/{contract['business_id']}/missions/{contract['mission_id']}/"
            f"runs/{contract['mission_run_id']}/artifacts/{safe_name}"
        )

    @classmethod
    def render_artifact_bytes(
        cls,
        *,
        artifact_type: str,
        title: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        metadata = metadata or {}

        if artifact_type == "json":
            payload = {
                "title": title,
                "content": content,
                "metadata": metadata,
                "status": "draft_preview",
            }
            return json.dumps(payload, sort_keys=True, indent=2).encode("utf-8")

        if artifact_type in {"document", "text", "markdown"}:
            body = [
                f"# {title}",
                "",
                content,
                "",
                "Status: draft_preview",
                "Generated by: AION Pilot",
            ]
            return "\n".join(body).encode("utf-8")

        if artifact_type == "spreadsheet":
            rows = [
                "field,value",
                f"title,{title}",
                f"status,draft_preview",
                f"generated_by,AION Pilot",
                f"content,{content.replace(',', ';')}",
            ]
            return "\n".join(rows).encode("utf-8")

        if artifact_type == "pdf":
            # Lightweight PDF-like placeholder bytes for the locked contract.
            # Real PDF rendering can be attached later behind the same safe path contract.
            body = (
                "%PDF-1.4\n"
                "% AION Pilot draft preview artifact\n"
                f"% Title: {title}\n"
                f"% Status: draft_preview\n"
                f"% Content: {content}\n"
                "%%EOF\n"
            )
            return body.encode("utf-8")

        raise PilotArtifactBuilderViolation(f"unsupported_artifact_type:{artifact_type}")

    @classmethod
    def create_draft_artifact(
        cls,
        *,
        container_root: str,
        contract: Dict[str, Any],
        title: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        rel_path = cls.build_container_relative_path(contract)
        full_path = Path(container_root) / rel_path
        cls._assert_container_path(container_root, full_path)

        artifact_bytes = cls.render_artifact_bytes(
            artifact_type=contract["artifact_type"],
            title=title,
            content=content,
            metadata=metadata or {},
        )

        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_bytes(artifact_bytes)

        artifact_hash = "sha256:" + hashlib.sha256(artifact_bytes).hexdigest()

        receipt = {
            "receipt_type": "aion.pilot.artifact_receipt.v1",
            "business_id": contract["business_id"],
            "mission_id": contract["mission_id"],
            "mission_run_id": contract["mission_run_id"],
            "step_id": contract["step_id"],
            "artifact_type": contract["artifact_type"],
            "artifact_name": contract["artifact_name"],
            "artifact_status": "draft_preview",
            "business_container_relative_path": rel_path,
            "artifact_hash": artifact_hash,
            "artifact_contract_hash": contract["artifact_contract_hash"],
            "live_external_side_effects": [],
            "blocked_actions": sorted(cls.BLOCKED_ACTIONS),
        }
        receipt["artifact_receipt_hash"] = cls.canonical_hash(receipt)

        return {
            "artifact_card_type": "aion.pilot.artifact_card.v1",
            "visible_in_cockpit": True,
            "artifact_type": contract["artifact_type"],
            "artifact_name": contract["artifact_name"],
            "status": "draft_preview",
            "business_container_relative_path": rel_path,
            "artifact_hash": artifact_hash,
            "artifact_receipt_hash": receipt["artifact_receipt_hash"],
            "receipt": receipt,
        }

    @classmethod
    def revise_draft_artifact(
        cls,
        *,
        container_root: str,
        previous_card: Dict[str, Any],
        contract: Dict[str, Any],
        title: str,
        revised_content: str,
        revision_note: str,
    ) -> Dict[str, Any]:
        previous_hash = previous_card["artifact_hash"]

        revised_card = cls.create_draft_artifact(
            container_root=container_root,
            contract=contract,
            title=title,
            content=revised_content,
            metadata={"revision_note": revision_note, "previous_artifact_hash": previous_hash},
        )

        if revised_card["artifact_hash"] == previous_hash:
            raise PilotArtifactBuilderViolation("revision_did_not_change_artifact_hash")

        revised_card["revision"] = {
            "revision_state": "draft_replaced",
            "previous_artifact_hash": previous_hash,
            "new_artifact_hash": revised_card["artifact_hash"],
            "revision_note": revision_note,
            "live_memory_mutated": False,
            "template_mutated": False,
            "provider_state_mutated": False,
            "reputation_mutated": False,
        }
        revised_card["revision"]["revision_hash"] = cls.canonical_hash(revised_card["revision"])
        return revised_card

    @classmethod
    def capture_feedback_event(
        cls,
        *,
        business_id: str,
        mission_id: str,
        mission_run_id: str,
        step_id: str,
        artifact_hash: str,
        feedback_type: str,
        feedback_text: str,
    ) -> Dict[str, Any]:
        if feedback_type not in {"approve", "reject", "revise", "stop", "retry", "continue"}:
            raise PilotArtifactBuilderViolation(f"unsupported_feedback_type:{feedback_type}")

        event = {
            "event_type": "aion.pilot.governed_feedback_event.v1",
            "business_id": business_id,
            "mission_id": mission_id,
            "mission_run_id": mission_run_id,
            "step_id": step_id,
            "artifact_hash": artifact_hash,
            "feedback_type": feedback_type,
            "feedback_text": feedback_text,
            "live_memory_mutated": False,
            "template_mutated": False,
            "provider_state_mutated": False,
            "reputation_mutated": False,
            "requires_governed_followup": feedback_type in {"approve", "revise", "continue", "retry"},
        }
        event["feedback_event_hash"] = cls.canonical_hash(event)
        return event
