"""add product_id fk to shipments

Revision ID: 1503c26aa96b
Revises: c8b4d3db34d7
Create Date: 2025-06-14 19:23:31.651568

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1503c26aa96b'
down_revision: Union[str, None] = 'c8b4d3db34d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # deals columns (existing)
    op.add_column('deals', sa.Column('quantity_kg', sa.Float(), nullable=False))
    op.add_column('deals', sa.Column('total_price', sa.Float(), nullable=False))
    # shipments: add product_id FK
    op.add_column(
        'shipments',
        sa.Column(
            'product_id',
            sa.Integer(),
            sa.ForeignKey('products.id', ondelete='CASCADE'),
            nullable=False,
            index=True
        )
    )
    op.create_index('ix_shipments_product_id', 'shipments', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # shipments: drop product_id FK/index
    op.drop_index('ix_shipments_product_id', table_name='shipments')
    op.drop_column('shipments', 'product_id')
    # deals columns
    op.drop_column('deals', 'total_price')
    op.drop_column('deals', 'quantity_kg')
    # ### end Alembic commands ###