"""Sync products schema to models

Revision ID: 5f40cc898654
Revises: a54affaa2a8e
Create Date: 2025-05-29 21:39:23.592671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f40cc898654'
down_revision: Union[str, None] = 'a54affaa2a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('deal_id', sa.Integer(), nullable=False))
    op.add_column('contracts', sa.Column('terms', sa.Text(), nullable=True))
    op.alter_column('contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_contracts_deal_id'), 'contracts', ['deal_id'], unique=False)
    op.create_foreign_key(None, 'contracts', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contracts', 'pdf_url')
    op.drop_column('contracts', 'generated_contract')
    op.drop_column('contracts', 'status')
    op.drop_column('contracts', 'prompt')
    op.add_column('deals', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('deals', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deals', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deals', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deals', 'status',
               existing_type=sa.VARCHAR(),
               server_default='pending',
               nullable=False)
    op.alter_column('deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_deals_buyer_id'), 'deals', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_deals_product_id'), 'deals', ['product_id'], unique=False)
    op.create_index(op.f('ix_deals_supplier_id'), 'deals', ['supplier_id'], unique=False)
    op.drop_constraint(op.f('deals_buyer_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_product_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_supplier_id_fkey'), 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'users', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deals', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deals', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('deals', 'pdf_url')
    op.drop_column('deals', 'supplier_email')
    op.drop_column('deals', 'quantity_kg')
    op.drop_column('deals', 'total_price')
    op.drop_column('deals', 'buyer_email')
    op.drop_column('deals', 'product_title')

    op.add_column('products', sa.Column('batch_number', sa.String(), nullable=True))
    op.add_column('products', sa.Column('trace_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('certificate_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('blockchain_tx_hash', sa.String(), nullable=True))

    # ── Add created_at with a server_default to backfill existing rows,
    #     then drop that default so future inserts use the model's default.
    op.add_column(
        'products',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()')
        )
    )
    op.alter_column('products', 'created_at', server_default=None)

    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('products', 'origin_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_products_owner_email'), 'products', ['owner_email'], unique=False)
    op.drop_constraint(op.f('products_owner_email_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['owner_email'], ['email'], ondelete='CASCADE')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_owner_email_fkey'), 'products', 'users', ['owner_email'], ['email'])
    op.drop_index(op.f('ix_products_owner_email'), table_name='products')
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'origin_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'blockchain_tx_hash')
    op.drop_column('products', 'certificate_url')
    op.drop_column('products', 'trace_id')
    op.drop_column('products', 'batch_number')
    op.add_column('deals', sa.Column('product_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('buyer_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('supplier_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(op.f('deals_supplier_id_fkey'), 'deals', 'users', ['supplier_id'], ['id'])
    op.create_foreign_key(op.f('deels_product_id_fkey'), 'deals', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('deals_buyer_id_fkey'), 'deals', 'users', ['buyer_id'], ['id'])
    op.drop_index(op.f('ix_deals_supplier_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_product_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_buyer_id'), table_name='deals')
    op.alter_column('deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('deels', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('deals', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deals', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deals', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('deals', 'price')
    op.add_column('contracts', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('generated_contract', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_index(op.f('ix_contracts_deal_id'), table_name='contracts')
    op.alter_column('contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('contracts', 'terms')
    op.drop_column('contracts', 'deal_id')
    # ### end Alembic commands ###