from __future__ import annotations

from typing import Any, Dict


def build_costa_conexion_topology_payload() -> Dict[str, Any]:
    """
    First real service-business seed for Costa Conexion.

    Returns a payload shaped to post directly to:
    /api/aion/business/topology/generate
    """

    workspace_id = "costa-conexion"

    return {
        "persist": True,
        "identity": {
            "workspace_id": workspace_id,
            "business_name": "Costa Conexion",
            "public_brand_name": "Costa Conexion",
            "business_type": "service_business",
            "country": "Spain",
            "region": "Almeria",
            "city": "Arboleas",
            "timezone": "Europe/Madrid",
            "currency": "EUR",
            "primary_domain": "costaconexion.es",
            "website_url": "https://costaconexion.es",
            "primary_email": "hello@costaconexion.es",
            "description": (
                "Local service directory and business promotion platform for Almeria, "
                "connecting residents with trusted local businesses and trades."
            ),
            "owner_role_id": "ceo-core",
            "onboarding_status": "draft",
            "active": True,
        },
        "channels": [
            {
                "id": "channel-website",
                "workspace_id": workspace_id,
                "name": "Website",
                "slug": "website",
                "channel_type": "website",
                "status": "active",
                "active": True,
                "platform_name": "Next.js",
                "primary_use_cases": ["search", "lead_capture", "business_profiles"],
            },
            {
                "id": "channel-whatsapp",
                "workspace_id": workspace_id,
                "name": "WhatsApp",
                "slug": "whatsapp",
                "channel_type": "whatsapp",
                "status": "active",
                "active": True,
                "platform_name": "WhatsApp",
                "primary_use_cases": ["deal_broadcasts", "customer_contact", "group_promotion"],
            },
            {
                "id": "channel-facebook",
                "workspace_id": workspace_id,
                "name": "Facebook Groups",
                "slug": "facebook-groups",
                "channel_type": "social",
                "status": "active",
                "active": True,
                "platform_name": "Facebook",
                "primary_use_cases": ["audience_growth", "business_outreach"],
            },
            {
                "id": "channel-print",
                "workspace_id": workspace_id,
                "name": "Printed Directory",
                "slug": "printed-directory",
                "channel_type": "offline",
                "status": "active",
                "active": True,
                "platform_name": "Print",
                "primary_use_cases": ["local_advertising", "brand_presence"],
            },
        ],
        "services": [
            {
                "id": "service-basic-listing",
                "workspace_id": workspace_id,
                "name": "Basic Business Listing",
                "slug": "basic-business-listing",
                "category": "directory_listing",
                "summary": "Entry-level directory profile for one town and one category.",
                "delivery_mode": "remote",
                "pricing_type": "fixed",
                "currency": "EUR",
                "service_area": ["almeria", "arboleas", "albox", "zurgena", "huercal-overa"],
                "requires_booking": False,
                "requires_quote": False,
                "active": True,
                "status": "active",
            },
            {
                "id": "service-growth-plan",
                "workspace_id": workspace_id,
                "name": "Growth Plan",
                "slug": "growth-plan",
                "category": "directory_subscription",
                "summary": "Multi-town paid plan with ad eligibility.",
                "delivery_mode": "remote",
                "pricing_type": "fixed",
                "currency": "EUR",
                "service_area": ["almeria", "arboleas", "albox", "zurgena", "huercal-overa"],
                "requires_booking": False,
                "requires_quote": False,
                "active": True,
                "status": "active",
            },
            {
                "id": "service-pro-plan",
                "workspace_id": workspace_id,
                "name": "Pro Plan",
                "slug": "pro-plan",
                "category": "directory_subscription",
                "summary": "Higher-tier subscription with broader placement and ad access.",
                "delivery_mode": "remote",
                "pricing_type": "fixed",
                "currency": "EUR",
                "service_area": ["almeria", "arboleas", "albox", "zurgena", "huercal-overa"],
                "requires_booking": False,
                "requires_quote": False,
                "active": True,
                "status": "active",
            },
            {
                "id": "service-top-search-ad",
                "workspace_id": workspace_id,
                "name": "Top Search Ad Slot",
                "slug": "top-search-ad-slot",
                "category": "advertising",
                "summary": "Scarce premium search placement per town/category.",
                "delivery_mode": "remote",
                "pricing_type": "fixed",
                "currency": "EUR",
                "service_area": ["almeria", "arboleas", "albox", "zurgena", "huercal-overa"],
                "requires_booking": False,
                "requires_quote": False,
                "active": True,
                "status": "active",
            },
            {
                "id": "service-print-ad",
                "workspace_id": workspace_id,
                "name": "Printed Directory Ad",
                "slug": "printed-directory-ad",
                "category": "advertising",
                "summary": "Local print placement in distributed directory copies.",
                "delivery_mode": "hybrid",
                "pricing_type": "fixed",
                "currency": "EUR",
                "service_area": ["almeria"],
                "requires_booking": False,
                "requires_quote": True,
                "active": True,
                "status": "active",
            },
        ],
        "revenue_streams": [
            {
                "id": "rev-subscriptions",
                "workspace_id": workspace_id,
                "name": "Subscriptions",
                "stream_type": "subscription",
                "cadence": "monthly",
                "status": "active",
                "currency": "EUR",
                "channel_ids": ["channel-website"],
                "service_ids": [
                    "service-basic-listing",
                    "service-growth-plan",
                    "service-pro-plan",
                ],
                "active": True,
            },
            {
                "id": "rev-digital-ads",
                "workspace_id": workspace_id,
                "name": "Digital Ad Sales",
                "stream_type": "advertising",
                "cadence": "monthly",
                "status": "active",
                "currency": "EUR",
                "channel_ids": ["channel-website", "channel-whatsapp", "channel-facebook"],
                "service_ids": ["service-top-search-ad"],
                "active": True,
            },
            {
                "id": "rev-print-ads",
                "workspace_id": workspace_id,
                "name": "Print Ad Sales",
                "stream_type": "advertising",
                "cadence": "variable",
                "status": "active",
                "currency": "EUR",
                "channel_ids": ["channel-print"],
                "service_ids": ["service-print-ad"],
                "active": True,
            },
        ],
        "cost_items": [
            {
                "id": "cost-software",
                "workspace_id": workspace_id,
                "name": "Software Stack",
                "cost_type": "software",
                "frequency": "monthly",
                "status": "active",
                "currency": "EUR",
                "active": True,
            },
            {
                "id": "cost-marketing",
                "workspace_id": workspace_id,
                "name": "Audience Growth Spend",
                "cost_type": "marketing",
                "frequency": "monthly",
                "status": "active",
                "currency": "EUR",
                "active": True,
            },
            {
                "id": "cost-print-production",
                "workspace_id": workspace_id,
                "name": "Print Production",
                "cost_type": "logistics",
                "frequency": "variable",
                "status": "active",
                "currency": "EUR",
                "active": True,
            },
        ],
        "payment_terms": [
            {
                "id": "payment-online",
                "workspace_id": workspace_id,
                "name": "Online Checkout Terms",
                "status": "active",
                "currency": "EUR",
                "payment_methods": ["card", "bank_transfer"],
                "timing": "upfront",
                "channel_ids": ["channel-website"],
                "service_ids": [
                    "service-growth-plan",
                    "service-pro-plan",
                    "service-top-search-ad",
                ],
                "active": True,
            },
            {
                "id": "payment-invoice",
                "workspace_id": workspace_id,
                "name": "Invoice Terms",
                "status": "active",
                "currency": "EUR",
                "payment_methods": ["bank_transfer"],
                "timing": "net_30",
                "channel_ids": ["channel-print", "channel-facebook"],
                "service_ids": ["service-print-ad"],
                "active": True,
            },
        ],
        "fulfillment_processes": [
            {
                "id": "fulfillment-digital-listing",
                "workspace_id": workspace_id,
                "name": "Digital Listing Activation",
                "fulfillment_mode": "digital_delivery",
                "status": "active",
                "service_ids": [
                    "service-basic-listing",
                    "service-growth-plan",
                    "service-pro-plan",
                ],
                "channel_ids": ["channel-website"],
                "stages": ["signup", "profile_setup", "review", "publish"],
                "handoff_points": ["sales_to_ops", "ops_to_support"],
                "requires_booking": False,
                "requires_scheduling": False,
                "requires_manual_confirmation": True,
                "active": True,
            },
            {
                "id": "fulfillment-ad-placement",
                "workspace_id": workspace_id,
                "name": "Ad Placement Workflow",
                "fulfillment_mode": "digital_delivery",
                "status": "active",
                "service_ids": ["service-top-search-ad", "service-print-ad"],
                "channel_ids": ["channel-website", "channel-whatsapp", "channel-print"],
                "stages": ["order", "asset_check", "placement", "live"],
                "handoff_points": ["sales_to_ops", "ops_to_support"],
                "requires_booking": False,
                "requires_scheduling": True,
                "requires_manual_confirmation": True,
                "active": True,
            },
        ],
        "functions": [
            {
                "id": "fn-marketing-audience-growth",
                "workspace_id": workspace_id,
                "department_key": "marketing",
                "key": "audience_growth",
                "name": "Audience Growth",
                "status": "active",
                "active": True,
                "channel_ids": ["channel-facebook", "channel-whatsapp"],
                "revenue_stream_ids": ["rev-digital-ads", "rev-print-ads"],
                "cost_item_ids": ["cost-marketing"],
            },
            {
                "id": "fn-sales-business-conversion",
                "workspace_id": workspace_id,
                "department_key": "sales",
                "key": "business_conversion",
                "name": "Business Conversion",
                "status": "active",
                "active": True,
                "channel_ids": ["channel-website", "channel-facebook", "channel-whatsapp"],
                "service_ids": [
                    "service-growth-plan",
                    "service-pro-plan",
                    "service-top-search-ad",
                    "service-print-ad",
                ],
                "revenue_stream_ids": [
                    "rev-subscriptions",
                    "rev-digital-ads",
                    "rev-print-ads",
                ],
                "payment_terms_ids": ["payment-online", "payment-invoice"],
            },
            {
                "id": "fn-operations-profile-publishing",
                "workspace_id": workspace_id,
                "department_key": "operations",
                "key": "profile_publishing",
                "name": "Profile Publishing",
                "status": "active",
                "active": True,
                "channel_ids": ["channel-website"],
                "service_ids": [
                    "service-basic-listing",
                    "service-growth-plan",
                    "service-pro-plan",
                ],
                "fulfillment_process_ids": ["fulfillment-digital-listing"],
            },
            {
                "id": "fn-operations-ad-placement",
                "workspace_id": workspace_id,
                "department_key": "operations",
                "key": "ad_placement",
                "name": "Ad Placement",
                "status": "active",
                "active": True,
                "channel_ids": ["channel-website", "channel-whatsapp", "channel-print"],
                "service_ids": ["service-top-search-ad", "service-print-ad"],
                "fulfillment_process_ids": ["fulfillment-ad-placement"],
                "cost_item_ids": ["cost-print-production"],
            },
            {
                "id": "fn-finance-billing",
                "workspace_id": workspace_id,
                "department_key": "finance",
                "key": "billing",
                "name": "Billing and Collections",
                "status": "active",
                "active": True,
                "revenue_stream_ids": [
                    "rev-subscriptions",
                    "rev-digital-ads",
                    "rev-print-ads",
                ],
                "payment_terms_ids": ["payment-online", "payment-invoice"],
                "cost_item_ids": ["cost-software", "cost-print-production"],
            },
            {
                "id": "fn-support-business-success",
                "workspace_id": workspace_id,
                "department_key": "support",
                "key": "business_success",
                "name": "Business Success",
                "status": "active",
                "active": True,
                "channel_ids": ["channel-whatsapp", "channel-website"],
                "service_ids": [
                    "service-basic-listing",
                    "service-growth-plan",
                    "service-pro-plan",
                    "service-top-search-ad",
                ],
            },
        ],
        "teams": [
            {
                "id": "team-marketing",
                "workspace_id": workspace_id,
                "name": "Marketing Team",
                "department_key": "marketing",
                "status": "active",
                "active": True,
                "human_agent_ids": ["human-kevin-founder"],
                "ai_agent_ids": ["ai-aion-sales"],
                "function_ids": [
                    "fn-marketing-audience-growth",
                ],
            },
            {
                "id": "team-commercial",
                "workspace_id": workspace_id,
                "name": "Commercial Team",
                "department_key": "sales",
                "status": "active",
                "active": True,
                "human_agent_ids": ["human-kevin-founder"],
                "ai_agent_ids": ["ai-aion-sales"],
                "function_ids": [
                    "fn-sales-business-conversion",
                ],
            },
            {
                "id": "team-delivery",
                "workspace_id": workspace_id,
                "name": "Delivery Team",
                "department_key": "operations",
                "status": "active",
                "active": True,
                "human_agent_ids": ["human-kevin-founder"],
                "ai_agent_ids": ["ai-aion-ops"],
                "function_ids": [
                    "fn-operations-profile-publishing",
                    "fn-operations-ad-placement",
                ],
            },
            {
                "id": "team-finance",
                "workspace_id": workspace_id,
                "name": "Finance Team",
                "department_key": "finance",
                "status": "active",
                "active": True,
                "human_agent_ids": ["human-kevin-founder"],
                "ai_agent_ids": ["ai-aion-finance"],
                "function_ids": [
                    "fn-finance-billing",
                ],
            },
            {
                "id": "team-support",
                "workspace_id": workspace_id,
                "name": "Support Team",
                "department_key": "support",
                "status": "active",
                "active": True,
                "human_agent_ids": ["human-kevin-founder"],
                "ai_agent_ids": ["ai-aion-support"],
                "function_ids": [
                    "fn-support-business-success",
                ],
            },
        ],
        "human_agents": [
            {
                "id": "human-kevin-founder",
                "workspace_id": workspace_id,
                "name": "Kevin Robinson",
                "role_title": "Founder",
                "department_key": "operations",
                "email": "hello@costaconexion.es",
                "status": "active",
                "active": True,
                "team_ids": [
                    "team-marketing",
                    "team-commercial",
                    "team-delivery",
                    "team-finance",
                    "team-support",
                ],
                "function_ids": [
                    "fn-marketing-audience-growth",
                    "fn-sales-business-conversion",
                    "fn-operations-profile-publishing",
                    "fn-operations-ad-placement",
                    "fn-finance-billing",
                    "fn-support-business-success",
                ],
                "capabilities": [
                    "marketing_direction",
                    "sales",
                    "publishing",
                    "ad_approval",
                    "billing_review",
                    "business_support",
                ],
            }
        ],
        "ai_agents": [
            {
                "id": "ai-aion-sales",
                "workspace_id": workspace_id,
                "name": "Aion Sales",
                "agent_type": "sales_assistant",
                "department_key": "sales",
                "role_id": "sales-core",
                "model_policy_ref": "openai_for_copy",
                "status": "active",
                "active": True,
                "team_ids": ["team-marketing", "team-commercial"],
                "function_ids": [
                    "fn-marketing-audience-growth",
                    "fn-sales-business-conversion",
                ],
                "capabilities": [
                    "lead_sorting",
                    "outreach_drafting",
                    "followup",
                ],
            },
            {
                "id": "ai-aion-ops",
                "workspace_id": workspace_id,
                "name": "Aion Ops",
                "agent_type": "operations_assistant",
                "department_key": "operations",
                "role_id": "ops-core",
                "model_policy_ref": "openai_for_copy",
                "status": "active",
                "active": True,
                "team_ids": ["team-delivery"],
                "function_ids": [
                    "fn-operations-profile-publishing",
                    "fn-operations-ad-placement",
                ],
                "capabilities": [
                    "publishing_checks",
                    "asset_validation",
                    "workflow_tracking",
                ],
            },
            {
                "id": "ai-aion-finance",
                "workspace_id": workspace_id,
                "name": "Aion Finance",
                "agent_type": "finance_assistant",
                "department_key": "finance",
                "role_id": "finance-core",
                "model_policy_ref": "openai_for_copy",
                "status": "active",
                "active": True,
                "team_ids": ["team-finance"],
                "function_ids": ["fn-finance-billing"],
                "capabilities": [
                    "invoice_followup",
                    "payment_tracking",
                    "collections_summary",
                ],
            },
            {
                "id": "ai-aion-support",
                "workspace_id": workspace_id,
                "name": "Aion Support",
                "agent_type": "support_assistant",
                "department_key": "support",
                "role_id": "support-core",
                "model_policy_ref": "openai_for_copy",
                "status": "active",
                "active": True,
                "team_ids": ["team-support"],
                "function_ids": ["fn-support-business-success"],
                "capabilities": [
                    "business_support",
                    "faq_response",
                    "issue_triage",
                ],
            },
        ],
    }