#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "=== syntax sweep: Goal Engine provider/container/boardroom files ==="
python -m py_compile \
  backend/modules/aion_business/providers/router.py \
  backend/modules/aion_business/providers/local_adapter.py \
  backend/modules/aion_business/providers/capability_manifest.py \
  backend/modules/aion_business/runtime/business_container_service.py \
  backend/modules/aion_business/runtime/business_container_repository.py \
  backend/modules/aion_business/contracts/business_containers.py \
  backend/modules/workflow_capsules/execution/workflow_capsule_dry_run.py \
  backend/modules/workflow_capsules/execution/goal_engine_dry_run_bridge.py

echo
echo "=== focused Goal Engine lock suite ==="
PYTHONPATH=. python -m pytest -q \
  backend/tests/workflow_capsules/test_aion_goal_engine_sprint1_gate_lock.py \
  backend/tests/workflow_capsules/test_aion_goal_engine_sprint1_completion_lock.py \
  backend/tests/workflow_capsules/test_aion_goal_engine_sprint2_outcome_evidence_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_evidence_pointers.py \
  backend/tests/workflow_capsules/test_goal_engine_evidence_pointers_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_evidence_source_preview_bundle_attachment.py \
  backend/tests/workflow_capsules/test_goal_engine_evidence_source_preview_bundle_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_evidence_pointer_viewer_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_evidence_source_visibility.py \
  backend/tests/workflow_capsules/test_goal_engine_outcome_metrics_layer.py \
  backend/tests/workflow_capsules/test_goal_engine_outcome_metrics_layer_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_variant_comparison_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_goal_engine_sprint3_checkpoint_resume_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_checkpoint_maintenance.py \
  backend/tests/workflow_capsules/test_goal_engine_checkpoint_maintenance_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_goal_engine_sprint4_experiment_runtime_lock.py \
  backend/tests/workflow_capsules/test_aion_goal_engine_sprint5_orchestrator_runtime_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_orchestrator_parent_child_aggregation.py \
  backend/tests/workflow_capsules/test_goal_engine_orchestrator_parent_child_preview_bundle_attachment.py \
  backend/tests/workflow_capsules/test_goal_engine_decomposition_preview_bundle_attachment.py \
  backend/tests/workflow_capsules/test_goal_engine_memory_preview_bundle_attachment.py \
  backend/tests/workflow_capsules/test_goal_engine_preview_bundle_cleanup_no_duplicate_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_preview_bundle_attachment_consolidation_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_orchestrator_parent_child_aggregation_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_contracts.py \
  backend/tests/workflow_capsules/test_goal_engine_registry.py \
  backend/tests/workflow_capsules/test_goal_engine_preview_builder_registry.py \
  backend/tests/workflow_capsules/test_goal_engine_preview_bundle_canonical_contract.py \
  backend/tests/workflow_capsules/test_goal_engine_versioning_reproducibility.py \
  backend/tests/workflow_capsules/test_goal_engine_versioning_reproducibility_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_workflow_dry_run_bridge.py \
  backend/tests/workflow_capsules/test_goal_engine_dry_run_bridge_preview_bundle_attachment.py \
  backend/tests/workflow_capsules/test_goal_engine_dry_run_bridge_attachment_location.py \
  backend/tests/workflow_capsules/test_goal_engine_step_trace_rows.py \
  backend/tests/workflow_capsules/test_goal_engine_step_trace_single_attachment_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_audit_trail.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_runtime_metrics_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_runtime_metrics_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_runtime_metrics_boardroom_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_degradation_feed_boardroom_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_audit_trail_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_local_adapter.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_capability_manifest.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_manifest_router_wiring.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_capability_routing_guard.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_capability_boardroom_payload.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_capability_boardroom_ui.py \
  backend/tests/workflow_capsules/test_goal_engine_provider_capability_manifest_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_business_container_persistence_layer.py \
  backend/tests/workflow_capsules/test_goal_engine_business_container_projection_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_business_container_guarded_mutations.py \
  backend/tests/workflow_capsules/test_goal_engine_business_container_projection_from_records.py \
  backend/tests/workflow_capsules/test_goal_engine_business_container_projection_boardroom_ui.py \
  backend/tests/workflow_capsules/test_goal_engine_business_container_persistence_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_live_payload_end_to_end_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_backend_payload_includes_runtime_preview.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_real_payload_source_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_visible_runtime_preview_style_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_visibility_mount_audit_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_live_preview_bundle_visibility_polish.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_live_kpi_panel_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_learning_panel_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_exploration_exploitation_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_decomposition_tree_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_parent_child_orchestration_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_orchestrated_glyphs_workflow_tabs_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_parent_goal_update_proposal.py \
  backend/tests/workflow_capsules/test_goal_engine_child_agent_conflict_preview.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_parent_goal_proposal_conflict_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_parent_goal_proposal_conflict_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_parent_goal_proposal_conflict_preview_bundle.py \
  backend/tests/workflow_capsules/test_goal_engine_multi_agent_execution_replay_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_multi_agent_execution_replay_history_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_multi_agent_execution_replay_history_backend.py \
  backend/tests/workflow_capsules/test_goal_engine_multi_agent_execution_replay_history_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_guarded_child_agent_execution_handoff.py \
  backend/tests/workflow_capsules/test_goal_engine_guarded_child_run_creation_request.py \
  backend/tests/workflow_capsules/test_goal_engine_guarded_child_run_creation_request_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_human_approved_child_run_creation_action.py \
  backend/tests/workflow_capsules/test_goal_engine_human_approved_child_run_creation_action_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_executor_bridge.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_executor_bridge_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_executor_bridge_preview_bundle_attachment.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_executor_bridge_boardroom_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_creation_bridge_runtime_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_creation_bridge_runtime_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_executor_bridge_preview_bundle_attachment_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_creation_end_to_end_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_child_run_creation_end_to_end_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_guarded_child_agent_execution_handoff_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_human_approved_conflict_resolution.py \
  backend/tests/workflow_capsules/test_goal_engine_human_approved_conflict_resolution_end_to_end_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_human_approved_conflict_resolution_end_to_end_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_human_approved_conflict_resolution_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_guarded_multi_agent_orchestration_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_recent_guarded_orchestration_panels_auto_mount_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_boardroom_parent_goal_proposal_conflict_payload_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_visible_boardroom_preview_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_visible_preview_bundle_ui_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_remaining_tasks_handover_lock_doc.py \
  backend/tests/workflow_capsules/test_goal_engine_focused_suite_membership_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_normalized_inbound_intent.py \
  backend/tests/workflow_capsules/test_aion_gateway_normalized_inbound_intent_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_fulfilment_job_core_preview.py \
  backend/tests/workflow_capsules/test_aion_gateway_fulfilment_job_core_preview_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_fulfilment_job_core_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_fulfilment_job_core_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_a2a_contract_schemas_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_a2a_contract_schemas_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_evidence_proof_hash_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_evidence_proof_hash_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_machine_a2a_trace_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_machine_a2a_trace_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_settlement_readiness_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_settlement_readiness_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_glyphchain_proof_commit_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_glyphchain_proof_commit_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_glyphchain_proof_commit_store_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_glyphchain_proof_commit_store_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_gateway_glyphchain_proof_receipt_lookup_lock.py \
  backend/tests/workflow_capsules/test_aion_gateway_glyphchain_proof_receipt_lookup_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_parallel_business_catalog_lock.py \
  backend/tests/workflow_capsules/test_aion_parallel_business_catalog_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_machine_cart_quote_handshake_lock.py \
  backend/tests/workflow_capsules/test_aion_machine_cart_quote_handshake_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_parallel_discovery_metadata_lock.py \
  backend/tests/workflow_capsules/test_aion_parallel_discovery_metadata_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_agent_channels_lock.py \
  backend/tests/workflow_capsules/test_aion_agent_channels_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_exception_recovery_loops_lock.py \
  backend/tests/workflow_capsules/test_aion_exception_recovery_loops_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_home_fixed_vertical_testbed_lock.py \
  backend/tests/workflow_capsules/test_aion_home_fixed_vertical_testbed_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_visibility_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_visibility_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_live_payload_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_live_payload_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_payload_mount_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_payload_mount_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_payload_bridge_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_payload_bridge_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_visible_render_path_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_visible_render_path_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_panel_polish_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_no_shell_takeover_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_parallel_twin_panel_polish_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_founder_override_preview_controls_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_founder_override_preview_controls_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_frontend_manual_smoke_confirmation_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_trust_reputation_summary_lock.py \
  backend/tests/workflow_capsules/test_aion_trust_reputation_summary_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_boardroom_trust_summary_visibility_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_boardroom_trust_summary_visibility_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_guarded_a2a_namespace_lock.py \
  backend/tests/workflow_capsules/test_aion_guarded_a2a_namespace_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_capabilities_catalog_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_capabilities_catalog_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_availability_quote_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_availability_quote_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_job_request_trace_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_job_request_trace_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_job_evidence_settlement_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_job_evidence_settlement_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_proof_receipt_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_proof_receipt_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_trust_summary_endpoint_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_trust_summary_endpoint_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_well_known_discovery_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_well_known_discovery_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_a2a_handshake_preview_lock.py \
  backend/tests/workflow_capsules/test_aion_a2a_handshake_preview_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_public_intent_gateway_lock.py \
  backend/tests/workflow_capsules/test_aion_public_intent_gateway_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_public_embed_widget_shell_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_public_embed_widget_shell_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_public_widget_request_mapping_lock.py \
  backend/tests/workflow_capsules/test_aion_public_widget_request_mapping_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_public_embed_widget_mapping_bridge_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_public_embed_widget_mapping_bridge_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_public_embed_guard_envelope_lock.py \
  backend/tests/workflow_capsules/test_aion_public_embed_guard_envelope_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_public_embed_human_review_handoff_lock.py \
  backend/tests/workflow_capsules/test_aion_public_embed_human_review_handoff_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_public_gateway_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_public_gateway_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_payment_coupling_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_payment_coupling_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_booking_side_effect_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_booking_side_effect_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_escrow_side_effect_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_escrow_side_effect_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_external_message_send_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_external_message_send_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_public_route_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_no_public_route_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_trace_drift_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_trace_drift_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_trust_reputation_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_trust_reputation_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_home_fixed_vertical_workflow_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_home_fixed_vertical_workflow_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_glyphchain_proof_receipt_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_glyphchain_proof_receipt_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_boardroom_ui_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_boardroom_ui_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_dynamic_pricing_hash_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_dynamic_pricing_hash_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_negotiation_boundary_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_negotiation_boundary_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_universal_vertical_adapter_compatibility_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_universal_vertical_adapter_compatibility_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase13_machine_metadata_deterministic_hash_regression_lock.py \
  backend/tests/workflow_capsules/test_aion_phase13_machine_metadata_deterministic_hash_regression_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_manifest_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_universal_vertical_adapter_contract_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_universal_vertical_adapter_contract_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_discovery_endpoint_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_discovery_endpoint_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_live_verification_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_live_verification_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_synthetic_agent_simulation_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_synthetic_agent_simulation_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_human_review_simulation_bridge_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_human_review_simulation_bridge_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_frontend_visibility_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_frontend_functional_wiring_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_frontend_actions_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_frontend_export_options_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_frontend_duplicate_cleanup_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_single_canonical_frontend_panel_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_payload_normalisation_lock.py \
  backend/tests/workflow_capsules/test_aion_phase14_agentmap_manifest_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_axo_ets_contract_foundation_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_ets_agentmap_preview_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_axo_readiness_dashboard_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_axo_anti_gaming_trust_rule_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_trusted_feedback_acceptance_preview_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_human_review_decision_preview_lock.py \
  backend/tests/workflow_capsules/test_aion_phase15_axo_ets_consolidation_closeout_lock.py \
  backend/tests/workflow_capsules/test_aion_phase20a_reasoning_packet_lock.py \
  backend/tests/workflow_capsules/test_aion_phase20a_reasoning_packet_lock_doc.py \
  backend/tests/workflow_capsules/test_aion_phase16_boardroom_advanced_runtime_drawer_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16_boardroom_front_page_simplification_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16c_founder_demo_ux_polish_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16d_founder_demo_ux_hardening_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16e_founder_demo_action_wiring_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16f_founder_demo_loop_functional_hero_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16g_boardroom_renderer_consolidation_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16h_founder_demo_visible_outputs_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16i_home_fixed_intake_quote_preview_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16j_founder_demo_ticket_run_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17a_website_intake_trigger_contract_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17b_home_fixed_website_adapter_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17c_public_intake_endpoint_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17d_workflow_trigger_bridge_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17f_website_intake_installation_panel_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17g_gmail_vault_intake_connector_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17h_functional_website_intake_actions_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17k_real_vault_gmail_ux_lock.py \
  backend/tests/workflow_capsules/test_aion_vault_gmail_consolidated_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17s_boardroom_enquiries_feed_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17t_clickable_enquiry_rows_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17u_remove_old_dummy_enquiry_card_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17l_simplified_vault_connector_ui_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17m_final_vault_connect_ux_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17n_gmail_oauth_success_refresh_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17j_vault_boardroom_gmail_bridge_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17g_home_fixed_live_test_actions_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17f_business_website_intake_installation_lock.py \
  backend/tests/workflow_capsules/test_aion_phase17e_boardroom_ticket_ui_simplification_lock.py \
  backend/tests/workflow_capsules/test_aion_phase16k_ticket_step_artifacts_lock.py \
  backend/tests/workflow_capsules/test_goal_engine_visible_step_trace_dry_run_ui_lock.py


python -m pytest -q backend/tests/workflow_capsules/test_aion_phase18_a2a_commercial_ticket_lock.py

python -m pytest -q backend/tests/workflow_capsules/test_aion_kindle_soft_ink_permanent_theme_lock.py

python -m pytest -q backend/tests/workflow_capsules/test_aion_desktop_packaging_hygiene_lock.py

python -m pytest -q backend/tests/workflow_capsules/test_aion_phase18_backend_contracts_lock.py

python -m pytest -q backend/tests/workflow_capsules/test_aion_phase18_preview_api_lock.py
