"use client";

import type { BoardroomModel } from "./boardroom.types";

export const BOARDROOM_DEMO_MODEL: BoardroomModel = {
  id: "workspace_brightline_demo",
  workspaceId: "brightline-telecoms",
  label: "BrightLine Telecoms",
  center: {
    revenue: "£284k",
    cash: "£91k",
    pipeline: "£412k",
    profit: "21%",
    health: "Stable",
  },
  seats: [
    {
      id: "seat_ceo",
      kind: "executive",
      label: "CEO",
      shortLabel: "CEO",
      owner: "Kevin",
      state: "healthy",
      x: 50,
      y: 14,
      metrics: [
        { id: "ceo_1", label: "Strategic Priority", value: "Scale delivery" },
        { id: "ceo_2", label: "Board Focus", value: "Cash + growth" },
      ],
      tasks: {
        open: 4,
        dueToday: 1,
        blocked: 0,
      },
    },
    {
      id: "seat_coo",
      kind: "executive",
      label: "COO",
      shortLabel: "COO",
      owner: "Operations Lead",
      state: "warning",
      x: 78,
      y: 28,
      metrics: [
        { id: "coo_1", label: "Fulfilment Capacity", value: "81%" },
        { id: "coo_2", label: "Escalations", value: "3 live" },
      ],
      tasks: {
        open: 7,
        dueToday: 2,
        blocked: 1,
      },
    },
    {
      id: "seat_marketing",
      kind: "department",
      label: "Marketing",
      shortLabel: "MKT",
      owner: "Growth Desk",
      state: "healthy",
      x: 82,
      y: 56,
      metrics: [
        { id: "mkt_1", label: "Lead Volume", value: "128 / wk" },
        { id: "mkt_2", label: "CAC", value: "£34" },
      ],
      tasks: {
        open: 9,
        dueToday: 3,
        blocked: 0,
      },
    },
    {
      id: "seat_sales",
      kind: "department",
      label: "Sales",
      shortLabel: "Sales",
      owner: "Revenue Desk",
      state: "healthy",
      x: 66,
      y: 82,
      metrics: [
        { id: "sales_1", label: "Close Rate", value: "28%" },
        { id: "sales_2", label: "Pipeline Velocity", value: "Good" },
      ],
      tasks: {
        open: 6,
        dueToday: 2,
        blocked: 0,
      },
    },
    {
      id: "seat_finance",
      kind: "department",
      label: "Finance",
      shortLabel: "FIN",
      owner: "Finance Desk",
      state: "warning",
      x: 34,
      y: 84,
      metrics: [
        { id: "fin_1", label: "Cash Runway", value: "7.2 mo" },
        { id: "fin_2", label: "Margin Drift", value: "-1.8%" },
      ],
      tasks: {
        open: 5,
        dueToday: 1,
        blocked: 1,
      },
    },
    {
      id: "seat_ops",
      kind: "department",
      label: "Operations",
      shortLabel: "OPS",
      owner: "Delivery Desk",
      state: "blocked",
      x: 18,
      y: 58,
      metrics: [
        { id: "ops_1", label: "Open Jobs", value: "43" },
        { id: "ops_2", label: "Capacity Risk", value: "High" },
      ],
      tasks: {
        open: 11,
        dueToday: 4,
        blocked: 3,
      },
    },
    {
      id: "seat_support",
      kind: "department",
      label: "Support",
      shortLabel: "SUP",
      owner: "Client Desk",
      state: "healthy",
      x: 22,
      y: 30,
      metrics: [
        { id: "sup_1", label: "SLA", value: "96.4%" },
        { id: "sup_2", label: "Open Tickets", value: "18" },
      ],
      tasks: {
        open: 4,
        dueToday: 1,
        blocked: 0,
      },
    },
  ],
  flows: [
    {
      id: "flow_marketing_sales",
      from: "seat_marketing",
      to: "seat_sales",
      label: "Leads",
      state: "normal",
    },
    {
      id: "flow_sales_finance",
      from: "seat_sales",
      to: "seat_finance",
      label: "Revenue",
      state: "normal",
    },
    {
      id: "flow_finance_ceo",
      from: "seat_finance",
      to: "seat_ceo",
      label: "Cash Truth",
      state: "warning",
    },
    {
      id: "flow_ops_coo",
      from: "seat_ops",
      to: "seat_coo",
      label: "Delivery Pressure",
      state: "blocked",
    },
    {
      id: "flow_support_coo",
      from: "seat_support",
      to: "seat_coo",
      label: "Service Load",
      state: "normal",
    },
    {
      id: "flow_coo_ceo",
      from: "seat_coo",
      to: "seat_ceo",
      label: "Exec Review",
      state: "warning",
    },
  ],
};