import type {
  BusinessPulse,
  BusinessWorkspace,
  Department,
  Seat,
  DepartmentFloors,
} from "./boardroom.domain";
import type { BoardroomRuntime } from "./boardroom.runtime";

export const DEMO_WORKSPACE: BusinessWorkspace = {
  id: "ws_costa_conexion",
  slug: "costa-conexion",
  name: "Costa Conexion",
  currency: "EUR",
  timezone: "Europe/Madrid",
  industry: "Local services marketplace",
};

export const DEMO_PULSE: BusinessPulse = {
  cash: {
    onHand: 12480,
    incoming30d: 9480,
    outgoing30d: 6120,
    runwayDays: 91,
  },
  sales: {
    revenue: 18640,
    orders: 73,
    conversionRate: 6.2,
    sellThroughRate: 64,
  },
  stock: {
    units: 0,
    value: 0,
    daysCover: 0,
    slowStockValue: 0,
    inTransitValue: 0,
  },
  ops: {
    backlog: 9,
    fulfilmentRate: 96,
    blockedJobs: 1,
    avgTurnaroundDays: 1.8,
  },
  finance: {
    creditorDays: 14,
    debtorDays: 9,
    grossMarginPct: 82,
  },
  risk: {
    cash: "low",
    stock: "low",
    demand: "medium",
    operations: "low",
  },
};

export const DEMO_DEPARTMENTS: Department[] = [
  { id: "dep_coo", key: "coo", name: "COO Core", owner: "Operations Lead", functions: [] },
  { id: "dep_marketing", key: "marketing", name: "Marketing", owner: "Growth Desk", functions: [] },
  { id: "dep_sales", key: "sales", name: "Sales", owner: "Revenue Desk", functions: [] },
  { id: "dep_operations", key: "operations", name: "Operations", owner: "Delivery Desk", functions: [] },
  { id: "dep_hr", key: "hr", name: "HR", owner: "People Desk", functions: [] },
  { id: "dep_support", key: "support", name: "Support", owner: "Client Desk", functions: [] },
  { id: "dep_finance", key: "finance", name: "Finance", owner: "Finance Desk", functions: [] },
  { id: "dep_ceo", key: "ceo", name: "CEO", owner: "Kevin", functions: [] },
  { id: "dep_aion", key: "aion", name: "AION", owner: "Executive AI", functions: [] },
  { id: "dep_openai", key: "openai", name: "OpenAI", owner: "External AI", functions: [] },
];

export const DEMO_SEATS: Seat[] = [
  {
    id: "seat_ceo",
    departmentKey: "ceo",
    label: "CEO",
    shortLabel: "CEO",
    owner: "Kevin",
    state: "healthy",
    openTasks: 4,
    blockedTasks: 0,
    dueToday: 1,
    goals: [
      {
        id: "goal_ceo_1",
        title: "Grow recurring local business revenue",
        ownerSeatId: "seat_ceo",
        status: "on_track",
        dueAt: "2026-04-30",
      },
      {
        id: "goal_ceo_2",
        title: "Keep execution safe in draft-first mode",
        ownerSeatId: "seat_ceo",
        status: "on_track",
        dueAt: "2026-04-20",
      },
    ],
    kpis: [
      {
        id: "kpi_ceo_1",
        seatId: "seat_ceo",
        label: "Runway",
        value: 91,
        unit: "d",
      },
      {
        id: "kpi_ceo_2",
        seatId: "seat_ceo",
        label: "Gross Margin",
        value: 82,
        unit: "%",
      },
      {
        id: "kpi_ceo_3",
        seatId: "seat_ceo",
        label: "Revenue",
        value: "€18.6k",
      },
    ],
    tasks: [
      {
        id: "task_ceo_1",
        seatId: "seat_ceo",
        title: "Review weekly boardroom operating pack",
        state: "in_progress",
        priority: "high",
        dueAt: "2026-04-14",
      },
      {
        id: "task_ceo_2",
        seatId: "seat_ceo",
        title: "Approve next marketing expansion towns",
        state: "todo",
        priority: "medium",
        dueAt: "2026-04-16",
      },
    ],
  },

  {
    id: "seat_coo",
    departmentKey: "coo",
    label: "COO",
    shortLabel: "COO",
    owner: "Operations Lead",
    state: "healthy",
    openTasks: 6,
    blockedTasks: 1,
    dueToday: 2,
    goals: [
      {
        id: "goal_coo_1",
        title: "Keep fulfilment above 95%",
        ownerSeatId: "seat_coo",
        status: "on_track",
        dueAt: "2026-04-22",
      },
      {
        id: "goal_coo_2",
        title: "Reduce blocked operational work to near zero",
        ownerSeatId: "seat_coo",
        status: "at_risk",
        dueAt: "2026-04-18",
      },
    ],
    kpis: [
      {
        id: "kpi_coo_1",
        seatId: "seat_coo",
        label: "Backlog",
        value: 9,
      },
      {
        id: "kpi_coo_2",
        seatId: "seat_coo",
        label: "Fulfilment Rate",
        value: 96,
        unit: "%",
      },
      {
        id: "kpi_coo_3",
        seatId: "seat_coo",
        label: "Blocked Jobs",
        value: 1,
      },
      {
        id: "kpi_coo_4",
        seatId: "seat_coo",
        label: "Cash View",
        value: "€12.5k",
      },
    ],
    tasks: [
      {
        id: "task_coo_1",
        seatId: "seat_coo",
        title: "Review dashboard alert thresholds",
        state: "in_progress",
        priority: "high",
        dueAt: "2026-04-14",
      },
      {
        id: "task_coo_2",
        seatId: "seat_coo",
        title: "Harden manual run policy checks",
        state: "blocked",
        priority: "high",
        dueAt: "2026-04-15",
      },
      {
        id: "task_coo_3",
        seatId: "seat_coo",
        title: "Approve next runtime queue changes",
        state: "todo",
        priority: "medium",
      },
    ],
  },

  {
    id: "seat_marketing",
    departmentKey: "marketing",
    label: "Marketing",
    shortLabel: "MKT",
    owner: "Growth Desk",
    state: "healthy",
    openTasks: 8,
    blockedTasks: 0,
    dueToday: 3,
    goals: [
      {
        id: "goal_mkt_1",
        title: "Increase qualified lead flow by 20%",
        ownerSeatId: "seat_marketing",
        status: "on_track",
        dueAt: "2026-04-30",
      },
      {
        id: "goal_mkt_2",
        title: "Keep draft approval cycle under 24 hours",
        ownerSeatId: "seat_marketing",
        status: "at_risk",
        dueAt: "2026-04-20",
      },
    ],
    kpis: [
      {
        id: "kpi_mkt_1",
        seatId: "seat_marketing",
        label: "Lead Volume",
        value: 148,
        unit: "/wk",
      },
      {
        id: "kpi_mkt_2",
        seatId: "seat_marketing",
        label: "CAC",
        value: "€18",
      },
      {
        id: "kpi_mkt_3",
        seatId: "seat_marketing",
        label: "CTR",
        value: 5.4,
        unit: "%",
      },
      {
        id: "kpi_mkt_4",
        seatId: "seat_marketing",
        label: "Qualified Leads",
        value: 42,
      },
    ],
    tasks: [
      {
        id: "task_mkt_1",
        seatId: "seat_marketing",
        title: "Review next 14 days of scheduled content",
        state: "in_progress",
        priority: "high",
        dueAt: "2026-04-14",
      },
      {
        id: "task_mkt_2",
        seatId: "seat_marketing",
        title: "Approve Facebook and Instagram drafts",
        state: "todo",
        priority: "high",
      },
      {
        id: "task_mkt_3",
        seatId: "seat_marketing",
        title: "Prepare LinkedIn repurpose variants",
        state: "todo",
        priority: "medium",
      },
    ],
  },

  {
    id: "seat_sales",
    departmentKey: "sales",
    label: "Sales",
    shortLabel: "Sales",
    owner: "Revenue Desk",
    state: "healthy",
    openTasks: 5,
    blockedTasks: 0,
    dueToday: 2,
    goals: [
      {
        id: "goal_sales_1",
        title: "Lift close rate above 30%",
        ownerSeatId: "seat_sales",
        status: "at_risk",
        dueAt: "2026-04-25",
      },
      {
        id: "goal_sales_2",
        title: "Reduce stale pipeline over 21 days",
        ownerSeatId: "seat_sales",
        status: "on_track",
        dueAt: "2026-04-19",
      },
    ],
    kpis: [
      {
        id: "kpi_sales_1",
        seatId: "seat_sales",
        label: "Close Rate",
        value: 27,
        unit: "%",
      },
      {
        id: "kpi_sales_2",
        seatId: "seat_sales",
        label: "Orders",
        value: 73,
      },
      {
        id: "kpi_sales_3",
        seatId: "seat_sales",
        label: "Sell Through",
        value: 64,
        unit: "%",
      },
      {
        id: "kpi_sales_4",
        seatId: "seat_sales",
        label: "Active Pipeline",
        value: "€21.8k",
      },
      {
        id: "kpi_sales_5",
        seatId: "seat_sales",
        label: "Won This Week",
        value: "€4.4k",
      },
      {
        id: "kpi_sales_6",
        seatId: "seat_sales",
        label: "Stale Deals",
        value: 6,
      },
    ],
    tasks: [
      {
        id: "task_sales_1",
        seatId: "seat_sales",
        title: "Follow up high-intent enquiries",
        state: "in_progress",
        priority: "high",
        dueAt: "2026-04-14",
      },
      {
        id: "task_sales_2",
        seatId: "seat_sales",
        title: "Review lost leads by town",
        state: "todo",
        priority: "medium",
      },
    ],
  },

  {
    id: "seat_finance",
    departmentKey: "finance",
    label: "Finance",
    shortLabel: "FIN",
    owner: "Finance Desk",
    state: "healthy",
    openTasks: 4,
    blockedTasks: 0,
    dueToday: 1,
    goals: [
      {
        id: "goal_fin_1",
        title: "Maintain runway above 75 days",
        ownerSeatId: "seat_finance",
        status: "on_track",
        dueAt: "2026-04-30",
      },
      {
        id: "goal_fin_2",
        title: "Keep debtor days below 14",
        ownerSeatId: "seat_finance",
        status: "on_track",
        dueAt: "2026-04-21",
      },
    ],
    kpis: [
      {
        id: "kpi_fin_1",
        seatId: "seat_finance",
        label: "Cash On Hand",
        value: "€12.5k",
      },
      {
        id: "kpi_fin_2",
        seatId: "seat_finance",
        label: "Debtor Days",
        value: 9,
        unit: "d",
      },
      {
        id: "kpi_fin_3",
        seatId: "seat_finance",
        label: "Creditor Days",
        value: 14,
        unit: "d",
      },
      {
        id: "kpi_fin_4",
        seatId: "seat_finance",
        label: "Gross Margin",
        value: 82,
        unit: "%",
      },
      {
        id: "kpi_fin_5",
        seatId: "seat_finance",
        label: "30d Net Cash",
        value: "€3.4k",
      },
    ],
    tasks: [
      {
        id: "task_fin_1",
        seatId: "seat_finance",
        title: "Review monthly ad spend against lead quality",
        state: "in_progress",
        priority: "medium",
        dueAt: "2026-04-15",
      },
      {
        id: "task_fin_2",
        seatId: "seat_finance",
        title: "Approve connector cost telemetry review",
        state: "todo",
        priority: "medium",
      },
    ],
  },

  {
    id: "seat_ops",
    departmentKey: "operations",
    label: "Operations",
    shortLabel: "OPS",
    owner: "Delivery Desk",
    state: "warning",
    openTasks: 7,
    blockedTasks: 1,
    dueToday: 3,
    goals: [
      {
        id: "goal_ops_1",
        title: "Reduce blocked jobs below 1",
        ownerSeatId: "seat_ops",
        status: "at_risk",
        dueAt: "2026-04-18",
      },
      {
        id: "goal_ops_2",
        title: "Restore turnaround below 2 days",
        ownerSeatId: "seat_ops",
        status: "on_track",
        dueAt: "2026-04-16",
      },
    ],
    kpis: [
      {
        id: "kpi_ops_1",
        seatId: "seat_ops",
        label: "Backlog",
        value: 9,
      },
      {
        id: "kpi_ops_2",
        seatId: "seat_ops",
        label: "Blocked Jobs",
        value: 1,
      },
      {
        id: "kpi_ops_3",
        seatId: "seat_ops",
        label: "Turnaround",
        value: 1.8,
        unit: "d",
      },
      {
        id: "kpi_ops_4",
        seatId: "seat_ops",
        label: "Fulfilment",
        value: 96,
        unit: "%",
      },
      {
        id: "kpi_ops_5",
        seatId: "seat_ops",
        label: "Capacity Used",
        value: 74,
        unit: "%",
      },
    ],
    tasks: [
      {
        id: "task_ops_1",
        seatId: "seat_ops",
        title: "Close remaining blocked fulfilment job",
        state: "in_progress",
        priority: "high",
        dueAt: "2026-04-14",
      },
      {
        id: "task_ops_2",
        seatId: "seat_ops",
        title: "Review local node failover path",
        state: "todo",
        priority: "medium",
      },
    ],
  },

  {
    id: "seat_hr",
    departmentKey: "hr",
    label: "HR",
    shortLabel: "HR",
    owner: "People Desk",
    state: "healthy",
    openTasks: 3,
    blockedTasks: 0,
    dueToday: 1,
    goals: [
      {
        id: "goal_hr_1",
        title: "Keep admin response under 48 hours",
        ownerSeatId: "seat_hr",
        status: "on_track",
        dueAt: "2026-04-30",
      },
    ],
    kpis: [
      {
        id: "kpi_hr_1",
        seatId: "seat_hr",
        label: "Open Admin Actions",
        value: 7,
      },
      {
        id: "kpi_hr_2",
        seatId: "seat_hr",
        label: "Avg Response",
        value: 1.2,
        unit: "d",
      },
      {
        id: "kpi_hr_3",
        seatId: "seat_hr",
        label: "Compliance",
        value: 99,
        unit: "%",
      },
    ],
    tasks: [
      {
        id: "task_hr_1",
        seatId: "seat_hr",
        title: "Review new contractor onboarding checklist",
        state: "in_progress",
        priority: "medium",
        dueAt: "2026-04-16",
      },
      {
        id: "task_hr_2",
        seatId: "seat_hr",
        title: "Chase missing documentation",
        state: "todo",
        priority: "low",
      },
    ],
  },

  {
    id: "seat_support",
    departmentKey: "support",
    label: "Support",
    shortLabel: "SUP",
    owner: "Client Desk",
    state: "healthy",
    openTasks: 4,
    blockedTasks: 0,
    dueToday: 1,
    goals: [
      {
        id: "goal_sup_1",
        title: "Maintain SLA above 95%",
        ownerSeatId: "seat_support",
        status: "on_track",
        dueAt: "2026-04-30",
      },
    ],
    kpis: [
      {
        id: "kpi_sup_1",
        seatId: "seat_support",
        label: "SLA",
        value: 97.1,
        unit: "%",
      },
      {
        id: "kpi_sup_2",
        seatId: "seat_support",
        label: "Open Tickets",
        value: 11,
      },
      {
        id: "kpi_sup_3",
        seatId: "seat_support",
        label: "Escalations",
        value: 1,
      },
    ],
    tasks: [
      {
        id: "task_sup_1",
        seatId: "seat_support",
        title: "Resolve premium listing issue",
        state: "todo",
        priority: "high",
      },
      {
        id: "task_sup_2",
        seatId: "seat_support",
        title: "Review repeat support topics",
        state: "in_progress",
        priority: "medium",
      },
    ],
  },
];

export const DEMO_FLOORS: DepartmentFloors = {
  sales: {
    departmentKey: "sales",
    agents: [
      {
        id: "sales_agent_sdr",
        departmentKey: "sales",
        entityType: "agent",
        label: "SDR",
        role: "Lead Qualification",
        displayTag: "AGENT",
        state: "healthy",
        workload: 14,
        throughput: 19,
        conversionPct: 39,
        assignedCount: 24,
      },
      {
        id: "sales_agent_closer",
        departmentKey: "sales",
        entityType: "agent",
        label: "Closer",
        role: "Proposal to Won",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 10,
        throughput: 11,
        conversionPct: 27,
        revenue: 4400,
        assignedCount: 13,
      },
      {
        id: "sales_agent_followup",
        departmentKey: "sales",
        entityType: "agent",
        label: "Follow-up",
        role: "Stale Deal Recovery",
        displayTag: "AGENT",
        state: "warning",
        workload: 8,
        throughput: 9,
        conversionPct: 17,
        assignedCount: 10,
      },
    ],
    stages: [
      {
        id: "sales_stage_new",
        departmentKey: "sales",
        entityType: "stage",
        label: "New Leads",
        count: 34,
        value: 6400,
        state: "healthy",
      },
      {
        id: "sales_stage_qualified",
        departmentKey: "sales",
        entityType: "stage",
        label: "Qualified",
        count: 22,
        value: 9800,
        state: "healthy",
      },
      {
        id: "sales_stage_proposal",
        departmentKey: "sales",
        entityType: "stage",
        label: "Proposal",
        count: 13,
        value: 7200,
        state: "warning",
      },
      {
        id: "sales_stage_won",
        departmentKey: "sales",
        entityType: "stage",
        label: "Won",
        count: 7,
        value: 4400,
        state: "healthy",
      },
      {
        id: "sales_stage_stale",
        departmentKey: "sales",
        entityType: "stage",
        label: "Stale",
        count: 6,
        value: 2400,
        state: "warning",
      },
    ],
    flows: [
      {
        id: "sales_flow_1",
        departmentKey: "sales",
        fromStageId: "sales_stage_new",
        toStageId: "sales_stage_qualified",
        count: 22,
        value: 9800,
        state: "healthy",
      },
      {
        id: "sales_flow_2",
        departmentKey: "sales",
        fromStageId: "sales_stage_qualified",
        toStageId: "sales_stage_proposal",
        count: 13,
        value: 7200,
        state: "healthy",
      },
      {
        id: "sales_flow_3",
        departmentKey: "sales",
        fromStageId: "sales_stage_proposal",
        toStageId: "sales_stage_won",
        count: 7,
        value: 4400,
        state: "healthy",
      },
      {
        id: "sales_flow_4",
        departmentKey: "sales",
        fromStageId: "sales_stage_proposal",
        toStageId: "sales_stage_stale",
        count: 6,
        value: 2400,
        state: "warning",
      },
    ],
  },

  finance: {
    departmentKey: "finance",
    agents: [
      {
        id: "finance_agent_collections",
        departmentKey: "finance",
        entityType: "agent",
        label: "Collections",
        role: "Receivables Recovery",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 8,
        throughput: 7,
        assignedCount: 9,
      },
      {
        id: "finance_agent_cashflow",
        departmentKey: "finance",
        entityType: "agent",
        label: "Cashflow",
        role: "Forecast and Liquidity",
        displayTag: "AGENT",
        state: "healthy",
        workload: 7,
        throughput: 5,
        assignedCount: 5,
      },
      {
        id: "finance_agent_payables",
        departmentKey: "finance",
        entityType: "agent",
        label: "Payables",
        role: "Supplier Timing Control",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 6,
        throughput: 8,
        assignedCount: 8,
      },
    ],
    stages: [
      {
        id: "finance_stage_invoiced",
        departmentKey: "finance",
        entityType: "stage",
        label: "Invoiced",
        count: 18,
        value: 18640,
        state: "healthy",
      },
      {
        id: "finance_stage_due",
        departmentKey: "finance",
        entityType: "stage",
        label: "Due",
        count: 7,
        value: 3800,
        state: "healthy",
      },
      {
        id: "finance_stage_overdue",
        departmentKey: "finance",
        entityType: "stage",
        label: "Overdue",
        count: 2,
        value: 940,
        state: "warning",
      },
      {
        id: "finance_stage_received",
        departmentKey: "finance",
        entityType: "stage",
        label: "Received",
        count: 15,
        value: 17200,
        state: "healthy",
      },
      {
        id: "finance_stage_suppliers",
        departmentKey: "finance",
        entityType: "stage",
        label: "Supplier Outflow",
        count: 6,
        value: 6120,
        state: "healthy",
      },
    ],
    flows: [
      {
        id: "finance_flow_1",
        departmentKey: "finance",
        fromStageId: "finance_stage_invoiced",
        toStageId: "finance_stage_due",
        count: 7,
        value: 3800,
        state: "healthy",
      },
      {
        id: "finance_flow_2",
        departmentKey: "finance",
        fromStageId: "finance_stage_due",
        toStageId: "finance_stage_received",
        count: 5,
        value: 2860,
        state: "healthy",
      },
      {
        id: "finance_flow_3",
        departmentKey: "finance",
        fromStageId: "finance_stage_due",
        toStageId: "finance_stage_overdue",
        count: 2,
        value: 940,
        state: "warning",
      },
      {
        id: "finance_flow_4",
        departmentKey: "finance",
        fromStageId: "finance_stage_received",
        toStageId: "finance_stage_suppliers",
        count: 6,
        value: 6120,
        state: "healthy",
      },
    ],
  },

  operations: {
    departmentKey: "operations",
    agents: [
      {
        id: "operations_agent_dispatch",
        departmentKey: "operations",
        entityType: "agent",
        label: "Dispatch",
        role: "Job Routing and Scheduling",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 10,
        throughput: 13,
        assignedCount: 14,
      },
      {
        id: "operations_agent_field",
        departmentKey: "operations",
        entityType: "agent",
        label: "Field Team",
        role: "Install and Fulfilment",
        displayTag: "HUMAN",
        state: "warning",
        workload: 12,
        throughput: 11,
        assignedCount: 12,
      },
      {
        id: "operations_agent_supply",
        departmentKey: "operations",
        entityType: "agent",
        label: "Supply",
        role: "Supplier and Stock Coordination",
        displayTag: "AGENT",
        state: "healthy",
        workload: 7,
        throughput: 8,
        assignedCount: 7,
      },
    ],
    stages: [
      {
        id: "operations_stage_backlog",
        departmentKey: "operations",
        entityType: "stage",
        label: "Backlog",
        count: 9,
        value: 9,
        state: "warning",
      },
      {
        id: "operations_stage_scheduled",
        departmentKey: "operations",
        entityType: "stage",
        label: "Scheduled",
        count: 8,
        value: 8,
        state: "healthy",
      },
      {
        id: "operations_stage_in_progress",
        departmentKey: "operations",
        entityType: "stage",
        label: "In Progress",
        count: 4,
        value: 4,
        state: "healthy",
      },
      {
        id: "operations_stage_blocked",
        departmentKey: "operations",
        entityType: "stage",
        label: "Blocked",
        count: 1,
        value: 1,
        state: "blocked",
      },
      {
        id: "operations_stage_completed",
        departmentKey: "operations",
        entityType: "stage",
        label: "Completed",
        count: 19,
        value: 19,
        state: "healthy",
      },
    ],
    flows: [
      {
        id: "operations_flow_1",
        departmentKey: "operations",
        fromStageId: "operations_stage_backlog",
        toStageId: "operations_stage_scheduled",
        count: 8,
        value: 8,
        state: "healthy",
      },
      {
        id: "operations_flow_2",
        departmentKey: "operations",
        fromStageId: "operations_stage_scheduled",
        toStageId: "operations_stage_in_progress",
        count: 4,
        value: 4,
        state: "healthy",
      },
      {
        id: "operations_flow_3",
        departmentKey: "operations",
        fromStageId: "operations_stage_in_progress",
        toStageId: "operations_stage_completed",
        count: 19,
        value: 19,
        state: "healthy",
      },
      {
        id: "operations_flow_4",
        departmentKey: "operations",
        fromStageId: "operations_stage_in_progress",
        toStageId: "operations_stage_blocked",
        count: 1,
        value: 1,
        state: "blocked",
      },
    ],
  },

  support: {
    departmentKey: "support",
    agents: [
      {
        id: "support_agent_triage",
        departmentKey: "support",
        entityType: "agent",
        label: "Triage",
        role: "Ticket Intake and Prioritisation",
        displayTag: "AGENT",
        state: "healthy",
        workload: 8,
        throughput: 15,
        assignedCount: 11,
      },
      {
        id: "support_agent_resolution",
        departmentKey: "support",
        entityType: "agent",
        label: "Resolution",
        role: "Issue Resolution",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 9,
        throughput: 12,
        assignedCount: 9,
      },
      {
        id: "support_agent_escalation",
        departmentKey: "support",
        entityType: "agent",
        label: "Escalation",
        role: "Critical Issue Escalation",
        displayTag: "AGENT",
        state: "warning",
        workload: 4,
        throughput: 3,
        assignedCount: 2,
      },
    ],
    stages: [
      {
        id: "support_stage_open",
        departmentKey: "support",
        entityType: "stage",
        label: "Open",
        count: 11,
        value: 11,
        state: "healthy",
      },
      {
        id: "support_stage_triaged",
        departmentKey: "support",
        entityType: "stage",
        label: "Triaged",
        count: 7,
        value: 7,
        state: "healthy",
      },
      {
        id: "support_stage_in_progress",
        departmentKey: "support",
        entityType: "stage",
        label: "In Progress",
        count: 3,
        value: 3,
        state: "healthy",
      },
      {
        id: "support_stage_escalated",
        departmentKey: "support",
        entityType: "stage",
        label: "Escalated",
        count: 1,
        value: 1,
        state: "warning",
      },
      {
        id: "support_stage_resolved",
        departmentKey: "support",
        entityType: "stage",
        label: "Resolved",
        count: 18,
        value: 18,
        state: "healthy",
      },
    ],
    flows: [
      {
        id: "support_flow_1",
        departmentKey: "support",
        fromStageId: "support_stage_open",
        toStageId: "support_stage_triaged",
        count: 7,
        value: 7,
        state: "healthy",
      },
      {
        id: "support_flow_2",
        departmentKey: "support",
        fromStageId: "support_stage_triaged",
        toStageId: "support_stage_in_progress",
        count: 3,
        value: 3,
        state: "healthy",
      },
      {
        id: "support_flow_3",
        departmentKey: "support",
        fromStageId: "support_stage_in_progress",
        toStageId: "support_stage_resolved",
        count: 18,
        value: 18,
        state: "healthy",
      },
      {
        id: "support_flow_4",
        departmentKey: "support",
        fromStageId: "support_stage_in_progress",
        toStageId: "support_stage_escalated",
        count: 1,
        value: 1,
        state: "warning",
      },
    ],
  },

  hr: {
    departmentKey: "hr",
    agents: [
      {
        id: "hr_agent_admin",
        departmentKey: "hr",
        entityType: "agent",
        label: "Admin",
        role: "Admin and Compliance Handling",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 6,
        throughput: 10,
        assignedCount: 7,
      },
      {
        id: "hr_agent_people",
        departmentKey: "hr",
        entityType: "agent",
        label: "People",
        role: "Staff Support and Follow-up",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 5,
        throughput: 7,
        assignedCount: 5,
      },
      {
        id: "hr_agent_hiring",
        departmentKey: "hr",
        entityType: "agent",
        label: "Hiring",
        role: "Hiring and Onboarding",
        displayTag: "AGENT",
        state: "healthy",
        workload: 4,
        throughput: 4,
        assignedCount: 3,
      },
    ],
    stages: [
      {
        id: "hr_stage_actions",
        departmentKey: "hr",
        entityType: "stage",
        label: "Open Actions",
        count: 7,
        value: 7,
        state: "healthy",
      },
      {
        id: "hr_stage_review",
        departmentKey: "hr",
        entityType: "stage",
        label: "Under Review",
        count: 4,
        value: 4,
        state: "healthy",
      },
      {
        id: "hr_stage_missing",
        departmentKey: "hr",
        entityType: "stage",
        label: "Missing Docs",
        count: 1,
        value: 1,
        state: "warning",
      },
      {
        id: "hr_stage_onboarding",
        departmentKey: "hr",
        entityType: "stage",
        label: "Onboarding",
        count: 2,
        value: 2,
        state: "healthy",
      },
      {
        id: "hr_stage_completed",
        departmentKey: "hr",
        entityType: "stage",
        label: "Completed",
        count: 12,
        value: 12,
        state: "healthy",
      },
    ],
    flows: [
      {
        id: "hr_flow_1",
        departmentKey: "hr",
        fromStageId: "hr_stage_actions",
        toStageId: "hr_stage_review",
        count: 4,
        value: 4,
        state: "healthy",
      },
      {
        id: "hr_flow_2",
        departmentKey: "hr",
        fromStageId: "hr_stage_review",
        toStageId: "hr_stage_completed",
        count: 12,
        value: 12,
        state: "healthy",
      },
      {
        id: "hr_flow_3",
        departmentKey: "hr",
        fromStageId: "hr_stage_review",
        toStageId: "hr_stage_missing",
        count: 1,
        value: 1,
        state: "warning",
      },
      {
        id: "hr_flow_4",
        departmentKey: "hr",
        fromStageId: "hr_stage_review",
        toStageId: "hr_stage_onboarding",
        count: 2,
        value: 2,
        state: "healthy",
      },
    ],
  },

  marketing: {
    departmentKey: "marketing",
    agents: [
      {
        id: "marketing_agent_campaigns",
        departmentKey: "marketing",
        entityType: "agent",
        label: "Campaigns",
        role: "Content Calendar and Scheduling",
        displayTag: "AGENT",
        state: "healthy",
        workload: 12,
        throughput: 18,
        assignedCount: 9,
        runtimeStatus: "running",
        queuedCount: 1,
        runningCount: 1,
        waitingApprovalCount: 1,
        failedCount: 0,
        completedCount: 8,
      },
      {
        id: "marketing_agent_creative",
        departmentKey: "marketing",
        entityType: "agent",
        label: "Creative",
        role: "Creative Production",
        displayTag: "HUMAN",
        state: "healthy",
        workload: 8,
        throughput: 10,
        assignedCount: 6,
        runtimeStatus: "completed",
        queuedCount: 0,
        runningCount: 0,
        waitingApprovalCount: 0,
        failedCount: 0,
        completedCount: 5,
      },
      {
        id: "marketing_agent_optimisation",
        departmentKey: "marketing",
        entityType: "agent",
        label: "Optimisation",
        role: "Performance and CAC Control",
        displayTag: "AGENT",
        state: "warning",
        workload: 9,
        throughput: 7,
        assignedCount: 5,
        runtimeStatus: "failed",
        queuedCount: 0,
        runningCount: 0,
        waitingApprovalCount: 0,
        failedCount: 1,
        completedCount: 2,
      },
    ],
    stages: [
      {
        id: "marketing_stage_planned",
        departmentKey: "marketing",
        entityType: "stage",
        label: "Planned",
        count: 12,
        value: 12,
        state: "healthy",
      },
      {
        id: "marketing_stage_live",
        departmentKey: "marketing",
        entityType: "stage",
        label: "Live",
        count: 6,
        value: 6,
        state: "healthy",
      },
      {
        id: "marketing_stage_testing",
        departmentKey: "marketing",
        entityType: "stage",
        label: "Testing",
        count: 4,
        value: 4,
        state: "healthy",
      },
      {
        id: "marketing_stage_waste",
        departmentKey: "marketing",
        entityType: "stage",
        label: "Waste",
        count: 2,
        value: 2,
        state: "warning",
      },
      {
        id: "marketing_stage_qualified",
        departmentKey: "marketing",
        entityType: "stage",
        label: "Qualified Leads",
        count: 42,
        value: 42,
        state: "healthy",
      },
    ],
    flows: [
      {
        id: "marketing_flow_1",
        departmentKey: "marketing",
        fromStageId: "marketing_stage_planned",
        toStageId: "marketing_stage_live",
        count: 6,
        value: 6,
        state: "healthy",
      },
      {
        id: "marketing_flow_2",
        departmentKey: "marketing",
        fromStageId: "marketing_stage_live",
        toStageId: "marketing_stage_testing",
        count: 4,
        value: 4,
        state: "healthy",
      },
      {
        id: "marketing_flow_3",
        departmentKey: "marketing",
        fromStageId: "marketing_stage_testing",
        toStageId: "marketing_stage_qualified",
        count: 42,
        value: 42,
        state: "healthy",
      },
      {
        id: "marketing_flow_4",
        departmentKey: "marketing",
        fromStageId: "marketing_stage_live",
        toStageId: "marketing_stage_waste",
        count: 2,
        value: 2,
        state: "warning",
      },
    ],
  },
};

export const DEMO_RUNTIME: BoardroomRuntime = {
  node: {
    status: "online",
    mode: "local_first",
    lastHeartbeatAt: "2026-04-11T20:45:00Z",
  },
  approvals: [
    {
      id: "approval_mkt_001",
      runId: "run_mkt_002",
      title: "Approve Facebook + Instagram spring upgrade drafts",
      status: "pending",
      requestedAt: "2026-04-11T20:20:00Z",
    },
  ],
  runs: [
    {
      id: "run_mkt_001",
      department_key: "marketing",
      agent_id: "marketing_agent_campaigns",
      workflow_key: "content_draft_queue_approval",
      workflow_label: "Content Draft + Queue + Approval",
      execution_mode: "draft_then_approval",
      status: "running",
      trigger_source: "manual",
      createdAt: "2026-04-11T20:05:00Z",
      startedAt: "2026-04-11T20:06:00Z",
      headline: "Spring telecom upgrade calendar set",
      summary: "Generating next content block and fitting it into the calendar",
      currentStepKey: "generate_caption",
      connectorKeys: ["facebook", "instagram"],
      outputCount: 2,
      steps: [
        {
          id: "step_mkt_001",
          runId: "run_mkt_001",
          key: "build_brief",
          label: "Build brief",
          status: "completed",
          startedAt: "2026-04-11T20:06:00Z",
          completedAt: "2026-04-11T20:07:00Z",
        },
        {
          id: "step_mkt_002",
          runId: "run_mkt_001",
          key: "generate_caption",
          label: "Generate caption",
          status: "running",
          startedAt: "2026-04-11T20:07:00Z",
        },
      ],
    },
    {
      id: "run_mkt_002",
      department_key: "marketing",
      agent_id: "marketing_agent_campaigns",
      workflow_key: "content_draft_queue_approval",
      workflow_label: "Content Draft + Queue + Approval",
      execution_mode: "draft_then_approval",
      status: "waiting_approval",
      trigger_source: "schedule",
      createdAt: "2026-04-11T19:40:00Z",
      startedAt: "2026-04-11T19:41:00Z",
      headline: "Weekend business spotlight post",
      summary: "Draft is ready and waiting for approval",
      currentStepKey: "approval_gate",
      approvalRequestId: "approval_mkt_001",
      connectorKeys: ["facebook", "instagram"],
      outputCount: 2,
      steps: [
        {
          id: "step_mkt_003",
          runId: "run_mkt_002",
          key: "build_brief",
          label: "Build brief",
          status: "completed",
          startedAt: "2026-04-11T19:41:00Z",
          completedAt: "2026-04-11T19:42:00Z",
        },
        {
          id: "step_mkt_004",
          runId: "run_mkt_002",
          key: "generate_draft",
          label: "Generate draft",
          status: "completed",
          startedAt: "2026-04-11T19:42:00Z",
          completedAt: "2026-04-11T19:44:00Z",
        },
        {
          id: "step_mkt_005",
          runId: "run_mkt_002",
          key: "approval_gate",
          label: "Approval gate",
          status: "waiting_approval",
          startedAt: "2026-04-11T19:44:00Z",
        },
      ],
    },
    {
      id: "run_mkt_003",
      department_key: "marketing",
      agent_id: "marketing_agent_creative",
      workflow_key: "creative_variant_refresh",
      workflow_label: "Creative Variant Refresh",
      execution_mode: "draft_only",
      status: "completed",
      trigger_source: "manual",
      createdAt: "2026-04-11T18:20:00Z",
      startedAt: "2026-04-11T18:21:00Z",
      completedAt: "2026-04-11T18:29:00Z",
      headline: "Arboleas + Albox creative variant pack",
      summary: "Completed 4 refreshed visual variants",
      connectorKeys: ["asset_library"],
      outputCount: 4,
      steps: [
        {
          id: "step_mkt_006",
          runId: "run_mkt_003",
          key: "collect_assets",
          label: "Collect assets",
          status: "completed",
          startedAt: "2026-04-11T18:21:00Z",
          completedAt: "2026-04-11T18:23:00Z",
        },
        {
          id: "step_mkt_007",
          runId: "run_mkt_003",
          key: "generate_variants",
          label: "Generate variants",
          status: "completed",
          startedAt: "2026-04-11T18:23:00Z",
          completedAt: "2026-04-11T18:28:00Z",
        },
      ],
    },
    {
      id: "run_mkt_004",
      department_key: "marketing",
      agent_id: "marketing_agent_optimisation",
      workflow_key: "waste_scan",
      workflow_label: "Ad Waste Scan",
      execution_mode: "draft_only",
      status: "failed",
      trigger_source: "system",
      createdAt: "2026-04-11T17:50:00Z",
      startedAt: "2026-04-11T17:51:00Z",
      failedAt: "2026-04-11T17:54:00Z",
      headline: "Spend anomaly check",
      summary: "Connector response timeout while pulling campaign spend",
      currentStepKey: "fetch_campaign_data",
      connectorKeys: ["meta_ads"],
      outputCount: 0,
      steps: [
        {
          id: "step_mkt_008",
          runId: "run_mkt_004",
          key: "fetch_campaign_data",
          label: "Fetch campaign data",
          status: "failed",
          startedAt: "2026-04-11T17:51:00Z",
          errorMessage: "Meta Ads connector timed out",
        },
      ],
    },
    {
      id: "run_mkt_005",
      department_key: "marketing",
      agent_id: "marketing_agent_campaigns",
      workflow_key: "content_draft_queue_approval",
      workflow_label: "Content Draft + Queue + Approval",
      execution_mode: "draft_then_approval",
      status: "queued",
      trigger_source: "schedule",
      createdAt: "2026-04-11T21:00:00Z",
      headline: "Monday morning post batch",
      summary: "Waiting for local node slot",
      connectorKeys: ["facebook", "instagram", "linkedin"],
      outputCount: 0,
      steps: [
        {
          id: "step_mkt_009",
          runId: "run_mkt_005",
          key: "build_brief",
          label: "Build brief",
          status: "pending",
        },
      ],
    },
  ],
};